/** Imágenes de la técnica de cada ejercicio: base abierta «free-exercise-db» (dominio público, licencia Unlicense).
 * Cada ejercicio tiene dos fotos (posición inicial y final) servidas por jsDelivr. */
const BASE = "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises";

/** id del catálogo de Apex → id del ejercicio en free-exercise-db. */
export const EXERCISE_IMG: Record<string, string> = {
  "press-banca": "Barbell_Bench_Press_-_Medium_Grip",
  "press-banca-inclinado": "Barbell_Incline_Bench_Press_-_Medium_Grip",
  "press-mancuernas": "Dumbbell_Bench_Press",
  "press-inclinado-mancuernas": "Incline_Dumbbell_Press",
  "aperturas": "Dumbbell_Flyes",
  "cruce-poleas": "Cable_Crossover",
  "fondos": "Dips_-_Chest_Version",
  "flexiones": "Pushups",
  "press-pecho-maquina": "Leverage_Chest_Press",
  "peck-deck": "Butterfly",
  "press-militar": "Standing_Military_Press",
  "press-hombro-mancuernas": "Dumbbell_Shoulder_Press",
  "press-arnold": "Arnold_Dumbbell_Press",
  "elevaciones-laterales": "Side_Lateral_Raise",
  "elevaciones-frontales": "Front_Dumbbell_Raise",
  "pajaros": "Reverse_Flyes",
  "face-pull": "Face_Pull",
  "press-hombro-maquina": "Machine_Shoulder_Military_Press",
  "triceps-polea": "Triceps_Pushdown",
  "press-frances": "EZ-Bar_Skullcrusher",
  "fondos-banco": "Bench_Dips",
  "patada-triceps": "Tricep_Dumbbell_Kickback",
  "triceps-cabeza": "Dumbbell_One-Arm_Triceps_Extension",
  "press-cerrado": "Close-Grip_Barbell_Bench_Press",
  "curl-barra": "Barbell_Curl",
  "curl-mancuernas": "Dumbbell_Alternate_Bicep_Curl",
  "curl-martillo": "Hammer_Curls",
  "curl-predicador": "Preacher_Curl",
  "curl-polea": "Standing_Biceps_Cable_Curl",
  "curl-inclinado": "Incline_Dumbbell_Curl",
  "curl-concentrado": "Concentration_Curls",
  "dominadas": "Pullups",
  "jalon-pecho": "Wide-Grip_Lat_Pulldown",
  "remo-barra": "Bent_Over_Barbell_Row",
  "remo-mancuerna": "One-Arm_Dumbbell_Row",
  "remo-polea": "Seated_Cable_Rows",
  "remo-t": "T-Bar_Row_with_Handle",
  "pullover": "Bent-Arm_Dumbbell_Pullover",
  "peso-muerto": "Barbell_Deadlift",
  "encogimientos": "Dumbbell_Shrug",
  "hiperextensiones": "Hyperextensions_Back_Extensions",
  "sentadilla": "Barbell_Squat",
  "sentadilla-frontal": "Front_Barbell_Squat",
  "sentadilla-goblet": "Goblet_Squat",
  "prensa": "Leg_Press",
  "zancadas": "Dumbbell_Lunges",
  "sentadilla-bulgara": "Split_Squat_with_Dumbbells",
  "extension-cuadriceps": "Leg_Extensions",
  "curl-femoral-tumbado": "Lying_Leg_Curls",
  "curl-femoral-sentado": "Seated_Leg_Curl",
  "peso-muerto-rumano": "Romanian_Deadlift",
  "hip-thrust": "Barbell_Hip_Thrust",
  "puente-gluteo": "Butt_Lift_Bridge",
  "abduccion-maquina": "Thigh_Abductor",
  "hack-squat": "Hack_Squat",
  "gemelos-pie": "Standing_Calf_Raises",
  "gemelos-sentado": "Seated_Calf_Raise",
  "step-up": "Dumbbell_Step_Ups",
  "plancha": "Plank",
  "crunch": "Crunches",
  "elevacion-piernas": "Hanging_Leg_Raise",
  "rueda-abdominal": "Ab_Roller",
  "russian-twist": "Russian_Twist",
  "plancha-lateral": "Side_Bridge",
  "crunch-polea": "Cable_Crunch",
  "remo-maquina": "Leverage_Iso_Row",
};

/** Las dos fotos [inicio, final] de un ejercicio, o null si no hay. */
export function exerciseFrames(catalogId: string): [string, string] | null {
  const id = EXERCISE_IMG[catalogId];
  return id ? [`${BASE}/${id}/0.jpg`, `${BASE}/${id}/1.jpg`] : null;
}
